name: Node CI #Build OSX Only (only need OSX for my instance), and upload compiled app as artifact
on: [push]
jobs:
  osx:
    runs-on: macOS-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn update and macdist
      run: |
        yarn update
        yarn run macdist
    - name: election-output filenames #cd into electron output dir, and grab filenames
      run: | 
        cd ./electron-output/ 
        echo OSX_zip=$(ls Companion-*.zip) >> $GITHUB_ENV 
        echo OSX_block=$(ls Companion-*.blockmap) >> $GITHUB_ENV
    - name: Upload Companion zip as artifact
      uses: 'actions/upload-artifact@v2'
      with:
        name: ${{ env.OSX_zip }}
        path: .
    - name: Upload Companion block as artifact
      uses: 'actions/upload-artifact@v2'
      with:
        name: ${{ env.OSX_block }}
        path: .